[project]
name = "shedding-hub"
version = "0.1.2"
readme = "README.md"
description = "Data and statistical models for biomarker shedding."
dependencies = [
    "pyaml",
    "requests",
    "pandas",
    "matplotlib"
]

[tool.setuptools.packages]
find = {}
